/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param resource The resource of the access
 * @param action The action of the access
 * @param effect The effect of the access
 */

data class Access (

    /* The resource of the access */
    @field:JsonProperty("resource")
    val resource: kotlin.String? = null,

    /* The action of the access */
    @field:JsonProperty("action")
    val action: kotlin.String? = null,

    /* The effect of the access */
    @field:JsonProperty("effect")
    val effect: kotlin.String? = null

)

