/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param contentType The content type of the icon
 * @param content The base64 encoded content of the icon
 */

data class Icon (

    /* The content type of the icon */
    @field:JsonProperty("content-type")
    val contentType: kotlin.String? = null,

    /* The base64 encoded content of the icon */
    @field:JsonProperty("content")
    val content: kotlin.String? = null

)

