/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The ldap configure properties
 *
 * @param ldapUrl The url of ldap service.
 * @param ldapSearchDn The search dn of ldap service.
 * @param ldapSearchPassword The search password of ldap service.
 * @param ldapBaseDn The base dn of ldap service.
 * @param ldapFilter The serach filter of ldap service.
 * @param ldapUid The serach uid from ldap service attributes.
 * @param ldapScope The serach scope of ldap service.
 * @param ldapConnectionTimeout The connect timeout of ldap service(second).
 * @param ldapVerifyCert Verify Ldap server certificate.
 */

data class LdapConf (

    /* The url of ldap service. */
    @field:JsonProperty("ldap_url")
    val ldapUrl: kotlin.String? = null,

    /* The search dn of ldap service. */
    @field:JsonProperty("ldap_search_dn")
    val ldapSearchDn: kotlin.String? = null,

    /* The search password of ldap service. */
    @field:JsonProperty("ldap_search_password")
    val ldapSearchPassword: kotlin.String? = null,

    /* The base dn of ldap service. */
    @field:JsonProperty("ldap_base_dn")
    val ldapBaseDn: kotlin.String? = null,

    /* The serach filter of ldap service. */
    @field:JsonProperty("ldap_filter")
    val ldapFilter: kotlin.String? = null,

    /* The serach uid from ldap service attributes. */
    @field:JsonProperty("ldap_uid")
    val ldapUid: kotlin.String? = null,

    /* The serach scope of ldap service. */
    @field:JsonProperty("ldap_scope")
    val ldapScope: kotlin.Long? = null,

    /* The connect timeout of ldap service(second). */
    @field:JsonProperty("ldap_connection_timeout")
    val ldapConnectionTimeout: kotlin.Long? = null,

    /* Verify Ldap server certificate. */
    @field:JsonProperty("ldap_verify_cert")
    val ldapVerifyCert: kotlin.Boolean? = null

)

