/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id id
 * @param name name
 * @param icon icon
 * @param maintainers maintainers
 * @param version version
 * @param source source
 */

data class Metadata (

    /* id */
    @field:JsonProperty("id")
    val id: kotlin.String? = null,

    /* name */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* icon */
    @field:JsonProperty("icon")
    val icon: kotlin.String? = null,

    /* maintainers */
    @field:JsonProperty("maintainers")
    val maintainers: kotlin.collections.List<kotlin.String>? = null,

    /* version */
    @field:JsonProperty("version")
    val version: kotlin.String? = null,

    /* source */
    @field:JsonProperty("source")
    val source: kotlin.String? = null

)

