/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id the project member id
 * @param projectId the project id
 * @param entityName the name of the group member.
 * @param roleName the name of the role
 * @param roleId the role id
 * @param entityId the id of entity, if the member is a user, it is user_id in user table. if the member is a user group, it is the user group's ID in user_group table.
 * @param entityType the entity's type, u for user entity, g for group entity.
 */

data class ProjectMemberEntity (

    /* the project member id */
    @field:JsonProperty("id")
    val id: kotlin.Int? = null,

    /* the project id */
    @field:JsonProperty("project_id")
    val projectId: kotlin.Int? = null,

    /* the name of the group member. */
    @field:JsonProperty("entity_name")
    val entityName: kotlin.String? = null,

    /* the name of the role */
    @field:JsonProperty("role_name")
    val roleName: kotlin.String? = null,

    /* the role id */
    @field:JsonProperty("role_id")
    val roleId: kotlin.Int? = null,

    /* the id of entity, if the member is a user, it is user_id in user table. if the member is a user group, it is the user group's ID in user_group table. */
    @field:JsonProperty("entity_id")
    val entityId: kotlin.Int? = null,

    /* the entity's type, u for user entity, g for group entity. */
    @field:JsonProperty("entity_type")
    val entityType: kotlin.String? = null

)

