/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The registry info contains the base info and capability declarations of the registry
 *
 * @param type The registry type
 * @param description The description
 * @param supportedResourceFilters The filters that the registry supports
 * @param supportedTriggers The triggers that the registry supports
 */

data class RegistryInfo(

    /* The registry type */
    @field:JsonProperty("type")
    val type: kotlin.String? = null,

    /* The description */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* The filters that the registry supports */
    @field:JsonProperty("supported_resource_filters")
    val supportedResourceFilters: kotlin.collections.List<FilterStyle>? = null,

    /* The triggers that the registry supports */
    @field:JsonProperty("supported_triggers")
    val supportedTriggers: kotlin.collections.List<kotlin.String>? = null

)

