/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The style of the resource filter
 *
 * @param key The endpoint key
 * @param `value` The endpoint value
 */

data class RegistryEndpoint (

    /* The endpoint key */
    @field:JsonProperty("key")
    val key: kotlin.String? = null,

    /* The endpoint value */
    @field:JsonProperty("value")
    val `value`: kotlin.String? = null

)

