/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * retention policy
 *
 * @param id
 * @param algorithm
 * @param rules
 * @param trigger
 * @param scope
 */

data class RetentionPolicy(

    @field:JsonProperty("id")
    val id: kotlin.Long? = null,

    @field:JsonProperty("algorithm")
    val algorithm: kotlin.String? = null,

    @field:JsonProperty("rules")
    val rules: kotlin.collections.List<RetentionRule>? = null,

    @field:JsonProperty("trigger")
    val trigger: RetentionRuleTrigger? = null,

    @field:JsonProperty("scope")
    val scope: RetentionPolicyScope? = null

)

