/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param executionId 
 * @param repository 
 * @param jobId 
 * @param status 
 * @param statusCode 
 * @param statusRevision 
 * @param startTime 
 * @param endTime 
 * @param total 
 * @param retained 
 */

data class RetentionExecutionTask (

    @field:JsonProperty("id")
    val id: kotlin.Long? = null,

    @field:JsonProperty("execution_id")
    val executionId: kotlin.Long? = null,

    @field:JsonProperty("repository")
    val repository: kotlin.String? = null,

    @field:JsonProperty("job_id")
    val jobId: kotlin.String? = null,

    @field:JsonProperty("status")
    val status: kotlin.String? = null,

    @field:JsonProperty("status_code")
    val statusCode: kotlin.Int? = null,

    @field:JsonProperty("status_revision")
    val statusRevision: kotlin.Long? = null,

    @field:JsonProperty("start_time")
    val startTime: kotlin.String? = null,

    @field:JsonProperty("end_time")
    val endTime: kotlin.String? = null,

    @field:JsonProperty("total")
    val total: kotlin.Int? = null,

    @field:JsonProperty("retained")
    val retained: kotlin.Int? = null

)

