/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param privateProjectCount The count of the private projects
 * @param privateRepoCount The count of the private repositories
 * @param publicProjectCount The count of the public projects
 * @param publicRepoCount The count of the public repositories
 * @param totalProjectCount The count of the total projects, only be seen by the system admin
 * @param totalRepoCount The count of the total repositories, only be seen by the system admin
 * @param totalStorageConsumption The total storage consumption of blobs, only be seen by the system admin
 */

data class Statistic (

    /* The count of the private projects */
    @field:JsonProperty("private_project_count")
    val privateProjectCount: kotlin.Long? = null,

    /* The count of the private repositories */
    @field:JsonProperty("private_repo_count")
    val privateRepoCount: kotlin.Long? = null,

    /* The count of the public projects */
    @field:JsonProperty("public_project_count")
    val publicProjectCount: kotlin.Long? = null,

    /* The count of the public repositories */
    @field:JsonProperty("public_repo_count")
    val publicRepoCount: kotlin.Long? = null,

    /* The count of the total projects, only be seen by the system admin */
    @field:JsonProperty("total_project_count")
    val totalProjectCount: kotlin.Long? = null,

    /* The count of the total repositories, only be seen by the system admin */
    @field:JsonProperty("total_repo_count")
    val totalRepoCount: kotlin.Long? = null,

    /* The total storage consumption of blobs, only be seen by the system admin */
    @field:JsonProperty("total_storage_consumption")
    val totalStorageConsumption: kotlin.Long? = null

)

