/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Supportted webhook event types and notify types.
 *
 * @param eventType 
 * @param notifyType 
 */

data class SupportedWebhookEventTypes (

    @field:JsonProperty("event_type")
    val eventType: kotlin.collections.List<kotlin.String>? = null,

    @field:JsonProperty("notify_type")
    val notifyType: kotlin.collections.List<kotlin.String>? = null

)

