openapi: 3.0.0
info:
  title: cloudapi_v2
  version: '2.0'
  description: buaa scs cloud api v2
  license:
    name: MIT
  contact:
    name: loheagn
    url: loheagn.com
    email: loheagn@icloud.com
  termsOfService: 'https://scs.buaa.edu.cn'
tags:
  - name: 作业
    description: 作业相关
  - name: 文件
    description: 文件相关
servers:
  - url: 'https://scs.buaa.edu.cn/api/v2'
paths:
  '/experiment/{experimentId}/assignment':
    parameters:
      - schema:
          type: string
        name: experimentId
        in: path
        required: true
    post:
      summary: 创建作业
      tags:
        - 作业
      operationId: post-experiment-experimentId-assignment
      responses:
        '200':
          $ref: '#/components/responses/Assignment'
      security:
        - Authorization: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                owner:
                  type: string
                file:
                  type: string
                  format: binary
              required:
                - owner
                - file
            examples: {}
        description: ''
      description: 第一次上传作业
  '/experiment/{experimentId}/assignment/{assignmentId}':
    parameters:
      - schema:
          type: integer
        name: experimentId
        in: path
        required: true
      - schema:
          type: integer
        name: assignmentId
        in: path
        required: true
    patch:
      summary: 重新上传作业
      operationId: patch-experiment-experimentId-assignment
      responses:
        '200':
          $ref: '#/components/responses/Assignment'
      security:
        - Authorization: []
      description: 重复上传作业，直接覆盖之前的作业
      tags:
        - 作业
      requestBody:
        $ref: '#/components/requestBodies/FileFormDataRequest'
  '/file/{fileId}':
    parameters:
      - schema:
          type: integer
        name: fileId
        in: path
        required: true
    get:
      summary: 下载文件
      tags:
        - 文件
      operationId: get-file-fileId
      security:
        - Authorization: []
      description: 下载文件，response是一个 content-type 为 application/octet-stream 的 二进制流
      responses:
        '200':
          $ref: '#/components/responses/RawFile'
    patch:
      summary: '修改文件'
      description: '修改文件'
      operationId: patch-file-fileId
      responses:
        '200':
          $ref: '#/components/responses/File'
      tags:
        - 文件
      security:
        - Authorization: []
      requestBody:
        $ref: '#/components/requestBodies/FileFormDataRequest'
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: apiKey
      in: header
      description: ''
      name: Authorization
  responses:
    Assignment:
      description: 作业相关的相应
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                id: 0
                studentId: string
                expId: 0
                courseId: 0
                fileId: 0
                createdAt: 0
                updatedAt: 0
            properties:
              id:
                type: integer
              studentId:
                type: string
                minLength: 4
                maxLength: 9
              expId:
                type: integer
              courseId:
                type: integer
              fileId:
                type: integer
              createdAt:
                type: integer
                description: 长整型时间戳
                format: int64
              updatedAt:
                type: integer
                description: 长整型时间戳
                format: int64
            required:
              - id
              - studentId
              - expId
              - courseId
              - fileId
              - createdAt
              - updatedAt
          examples:
            example-1:
              value:
                id: 22
                studentId: '15131049'
                fileId: 40
                expId: 1062
                courseId: 438
                createdAt: 1643361519220
                updatedAt: 1643363133061
    RawFile:
      description: 文件二进制流
      content:
        application/octet-stream:
          schema:
            type: object
    File:
      description: 文件在数据库中的描述
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                id: 39
                name: example.png
                storeType: S3
                storeName: 0e17e5b6-4bd0-480c-9ea7-256adbd6fd9b
                storePath: bucket
                uploadTime: 1643366839000
                fileType: Assignment
                size: 880188
                uploader: admin
                owner: '15131049'
                createdAt: 1643361520223
                updatedAt: 1643366839703
            properties:
              id:
                type: integer
                format: int32
              name:
                type: string
                minLength: 1
              storeType:
                type: string
                minLength: 1
              storeName:
                type: string
                minLength: 1
              storePath:
                type: string
                minLength: 1
              uploadTime:
                type: integer
                format: int64
                description: 时间戳
              fileType:
                type: string
                minLength: 1
              size:
                type: integer
                format: int64
              uploader:
                type: string
                minLength: 1
              owner:
                type: string
                minLength: 1
              createdAt:
                type: integer
                format: int64
                description: 时间戳
              updatedAt:
                type: integer
                format: int64
                description: 时间戳
            required:
              - id
              - name
              - storeType
              - storeName
              - storePath
              - uploadTime
              - fileType
              - size
              - uploader
              - owner
              - createdAt
              - updatedAt
          examples:
            example-1:
              value:
                id: 39
                name: example.png
                storeType: S3
                storeName: 0e17e5b6-4bd0-480c-9ea7-256adbd6fd9b
                storePath: bucket
                uploadTime: 1643366839000
                fileType: Assignment
                size: 880188
                uploader: admin
                owner: '15131049'
                createdAt: 1643361520223
                updatedAt: 1643366839703
  requestBodies:
    FileFormDataRequest:
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary
