/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models

import cn.edu.buaa.scs.controller.models.AssessmentInfoResponse

/**
 * 
 * @param id 
 * @param peerInfoList 
 * @param peerScore 互评得到的分数
 * @param finalScore 教师干预后的分数
 */
data class AssignmentPeerAssessmentResultResponse(
    val id: kotlin.Int,
    val peerInfoList: kotlin.collections.List<AssessmentInfoResponse>,
    /* 互评得到的分数 */
    val peerScore: kotlin.Double? = null,
    /* 教师干预后的分数 */
    val finalScore: kotlin.Double? = null
) 

