/**
 * cloudapi_v2
 * buaa scs cloud api v2
 *
 * The version of the OpenAPI document: 2.0
 * Contact: loheagn@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package cn.edu.buaa.scs.controller.models


/**
 *
 * @param id 用户的学工号，小写
 * @param token
 */
data class Authentication(
    /* 用户的学工号，小写 */
    val id: kotlin.String,
    val token: kotlin.String
)

