/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param id 
 * @param name 
 * @param teacher 任课教师姓名
 * @param termId 
 * @param createTime 
 * @param departmentId 
 */
data class CourseResponse(
    val id: kotlin.Int,
    val name: kotlin.String,
    /* 任课教师姓名 */
    val teacher: kotlin.String,
    val termId: kotlin.Int,
    val createTime: kotlin.String,
    val departmentId: kotlin.String
) 

