/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models

import cn.edu.buaa.scs.controller.models.CourseResponse
import cn.edu.buaa.scs.controller.models.ExpVmInfo
import cn.edu.buaa.scs.controller.models.ExperimentWorkflowConfigurationResponse
import cn.edu.buaa.scs.controller.models.FileResponse

/**
 * 
 * @param id 
 * @param name 
 * @param type 
 * @param detail 
 * @param createTime 
 * @param startTime 
 * @param endTime 
 * @param deadline 
 * @param isPeerAssessment 
 * @param peerAssessmentDeadline 
 * @param appealDeadline 
 * @param peerAssessmentRules 
 * @param peerAssessmentStart 
 * @param sentEmail 
 * @param course 
 * @param resourceFile 
 * @param vm 
 * @param workflowExperimentConfiguration 
 */
data class ExperimentResponse(
    val id: kotlin.Int,
    val name: kotlin.String,
    val type: kotlin.Boolean,
    val detail: kotlin.String,
    val createTime: kotlin.String,
    val startTime: kotlin.String,
    val endTime: kotlin.String,
    val deadline: kotlin.String,
    val isPeerAssessment: kotlin.Boolean,
    val peerAssessmentDeadline: kotlin.String,
    val appealDeadline: kotlin.String,
    val peerAssessmentRules: kotlin.String,
    val peerAssessmentStart: kotlin.Boolean,
    val sentEmail: kotlin.Boolean,
    val course: CourseResponse,
    val resourceFile: FileResponse? = null,
    val vm: ExpVmInfo? = null,
    val workflowExperimentConfiguration: ExperimentWorkflowConfigurationResponse? = null
) 

