/**
 * cloudapi_v2
 * buaa scs cloud api v2
 *
 * The version of the OpenAPI document: 2.0
 * Contact: loheagn@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package cn.edu.buaa.scs.controller.models


/**
 * 某次实验所分配的虚拟机情况
 * @param applyId
 * @param expectedNum
 * @param actualNum
 * @param status 虚拟机申请状态
 */
data class ExpVmInfo(
    val applyId: kotlin.String,
    val expectedNum: kotlin.Int,
    val actualNum: kotlin.Int,
    /* 虚拟机申请状态 */
    val status: kotlin.Int
)

