/**
 * cloudapi_v2
 * buaa scs cloud api v2
 *
 * The version of the OpenAPI document: 2.0
 * Contact: loheagn@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package cn.edu.buaa.scs.controller.models


/**
 *
 * @param hostPrefix
 * @param owner
 * @param repo
 * @param tags
 * @param pushTime
 */
data class Image(
    val hostPrefix: kotlin.String,
    val owner: kotlin.String,
    val repo: kotlin.String,
    val tags: kotlin.collections.List<kotlin.String>,
    val pushTime: kotlin.Long
) 

