/**
 * cloudapi_v2
 * buaa scs cloud api v2
 *
 * The version of the OpenAPI document: 2.0
 * Contact: loheagn@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package cn.edu.buaa.scs.controller.models


/**
 *
 * @param hostPrefix
 * @param owner
 * @param repo
 * @param tag
 * @param status UNDO, DOING, SUCCESS, FAIL
 * @param createdTime
 * @param endTime
 */
data class ImageBuildTask(
    val hostPrefix: kotlin.String,
    val owner: kotlin.String,
    val repo: kotlin.String,
    val tag: kotlin.String,
    /* UNDO, DOING, SUCCESS, FAIL */
    val status: kotlin.String,
    val createdTime: kotlin.Long,
    val endTime: kotlin.Long
)

