/**
 * cloudapi_v2
 * buaa scs cloud api v2
 *
 * The version of the OpenAPI document: 2.0
 * Contact: loheagn@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package cn.edu.buaa.scs.controller.models

import cn.edu.buaa.scs.controller.models.ImageBuilderSpecContextGit
import cn.edu.buaa.scs.controller.models.ImageBuilderSpecContextS3

/**
 *
 * @param git
 * @param raw
 * @param s3
 */
data class ImageBuilderSpecContext(
    val git: ImageBuilderSpecContextGit? = null,
    val raw: kotlin.String? = null,
    val s3: ImageBuilderSpecContextS3? = null
)

