/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param content 
 * @param processStatus 
 * @param processContent 
 */
data class PatchPeerAppealRequest(
    val content: kotlin.String? = null,
    val processStatus: kotlin.Int? = null,
    val processContent: kotlin.String? = null
) 

