/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param displayName 
 * @param expId 
 * @param description 
 * @param isPersonal 表示是否是个人项目，默认为false
 */
data class PostProjectsRequest(
    val displayName: kotlin.String,
    val expId: kotlin.Int? = null,
    val description: kotlin.String? = null,
    /* 表示是否是个人项目，默认为false */
    val isPersonal: kotlin.Boolean? = null
) 

