/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param name 项目名称， 不允许使用与他人或自己重复的项目名称， 且项目名称必须符合 RFC1035 规范
 * @param expId 
 * @param isPersonal 是否是个人项目。个人项目不允许添加其他成员。默认为false
 */
data class PostProjectsRequest1(
    /* 项目名称， 不允许使用与他人或自己重复的项目名称， 且项目名称必须符合 RFC1035 规范 */
    val name: kotlin.String,
    val expId: kotlin.Int? = null,
    /* 是否是个人项目。个人项目不允许添加其他成员。默认为false */
    val isPersonal: kotlin.Boolean? = null
) 

