/**
 * cloudapi_v2
 * buaa scs cloud api v2
 *
 * The version of the OpenAPI document: 2.0
 * Contact: loheagn@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package cn.edu.buaa.scs.controller.models


/**
 *
 * @param userId
 * @param password
 * @param captchaToken
 * @param captchaText
 */
data class PostLoginRequest(
    val userId: kotlin.String,
    val password: kotlin.String,
    val captchaToken: kotlin.String,
    val captchaText: kotlin.String
)

