/**
 * cloudapi_v2
 * buaa scs cloud api v2
 *
 * The version of the OpenAPI document: 2.0
 * Contact: loheagn@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package cn.edu.buaa.scs.controller.models

/**
 *
 * @param id
 * @param name
 * @param ownerId
 * @param used
 * @param usedRecordList
 * @param exchangeRecordList
 */
data class ResourcePool(
    val id: kotlin.String,
    val name: kotlin.String,
    val ownerId: kotlin.String,
    val used: Resource,
    val usedRecordList: kotlin.collections.List<ResourceUsedRecord>,
    val exchangeRecordList: kotlin.collections.List<ResourceExchangeRecord>
) 

