/**
 * cloudapi_v2
 * buaa scs cloud api v2
 *
 * The version of the OpenAPI document: 2.0
 * Contact: loheagn@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package cn.edu.buaa.scs.controller.models

/**
 *
 * @param id
 * @param sender
 * @param &#x60;receiver&#x60;
 * @param resource
 * @param time
 */
data class ResourceExchangeRecord(
    val id: kotlin.String,
    val sender: kotlin.String,
    val `receiver`: kotlin.String,
    val resource: Resource,
    val time: kotlin.Long
) 

