/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models

import cn.edu.buaa.scs.controller.models.ExpVmInfo

/**
 * 
 * @param id 
 * @param name 
 * @param type 表示是实验还是作业。false表示是作业，true表示是实验
 * @param detail 
 * @param createTime 
 * @param startTime 
 * @param endTime 
 * @param deadline 
 * @param isPeerAssessment 
 * @param peerAssessmentDeadline 
 * @param appealDeadline 
 * @param peerAssessmentRules 
 * @param peerAssessmentStart 
 * @param sentEmail 
 * @param submittedAssignmentsCnt 已提交作业的人数
 * @param resource 
 * @param vm 
 */
data class StatCourseExp(
    val id: kotlin.Int,
    val name: kotlin.String,
    /* 表示是实验还是作业。false表示是作业，true表示是实验 */
    val type: kotlin.Boolean,
    val detail: kotlin.String,
    val createTime: kotlin.String,
    val startTime: kotlin.String,
    val endTime: kotlin.String,
    val deadline: kotlin.String,
    val isPeerAssessment: kotlin.Boolean,
    val peerAssessmentDeadline: kotlin.String,
    val appealDeadline: kotlin.String,
    val peerAssessmentRules: kotlin.String,
    val peerAssessmentStart: kotlin.Boolean,
    val sentEmail: kotlin.Boolean,
    /* 已提交作业的人数 */
    val submittedAssignmentsCnt: kotlin.Int,
    val resource: kotlin.String? = null,
    val vm: ExpVmInfo? = null
) 

