apiVersion: batch/v1
kind: Job
metadata:
  name: image-build-007
  namespace: iobs
spec:
  template:
    spec:
      volumes:
        - name: workspace
          emptyDir: { }
        - name: push-secret
          secret:
            secretName: push-secret
            items:
              - key: .dockerconfigjson
                path: config.json
      initContainers:
        - name: prepare-workspace
          image: bitnami/git:2
          command: [ "/bin/sh", "-c", "git clone https://99131009:kqbL65Hrwy96c@scs.buaa.edu.cn/git/SY2121108/loheagn-private.git /target" ]
          volumeMounts:
            - mountPath: /target
              name: workspace
      containers:
        - name: builder
          image: scs.buaa.edu.cn:8081/iobs/kaniko-executor
          args:
            - "--dockerfile=Dockerfile"
            - "--context=dir:///workspace"
            - "--destination=scs.buaa.edu.cn:8081/iobs/kaniko-test:git"
          volumeMounts:
            - mountPath: /workspace
              name: workspace
            - mountPath: /kaniko/.docker/
              name: push-secret
      restartPolicy: Never