/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The accessory of the artifact
 *
 * @param id The ID of the accessory
 * @param artifactId The artifact id of the accessory
 * @param subjectArtifactId The subject artifact id of the accessory
 * @param propertySize The artifact size of the accessory
 * @param digest The artifact digest of the accessory
 * @param type The artifact size of the accessory
 * @param icon The icon of the accessory
 * @param creationTime The creation time of the accessory
 */

data class Accessory (

    /* The ID of the accessory */
    @field:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* The artifact id of the accessory */
    @field:JsonProperty("artifact_id")
    val artifactId: kotlin.Long? = null,

    /* The subject artifact id of the accessory */
    @field:JsonProperty("subject_artifact_id")
    val subjectArtifactId: kotlin.Long? = null,

    /* The artifact size of the accessory */
    @field:JsonProperty("size")
    val propertySize: kotlin.Long? = null,

    /* The artifact digest of the accessory */
    @field:JsonProperty("digest")
    val digest: kotlin.String? = null,

    /* The artifact size of the accessory */
    @field:JsonProperty("type")
    val type: kotlin.String? = null,

    /* The icon of the accessory */
    @field:JsonProperty("icon")
    val icon: kotlin.String? = null,

    /* The creation time of the accessory */
    @field:JsonProperty("creation_time")
    val creationTime: java.time.OffsetDateTime? = null

)

