/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * a model for all the error response coming from harbor
 *
 * @param code The error code
 * @param message The error message
 */

data class Error (

    /* The error code */
    @field:JsonProperty("code")
    val code: kotlin.String? = null,

    /* The error message */
    @field:JsonProperty("message")
    val message: kotlin.String? = null

)

