/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param id The ID of execution
 * @param vendorType The vendor type of execution
 * @param vendorId The vendor id of execution
 * @param status The status of execution
 * @param statusMessage The status message of execution
 * @param metrics
 * @param trigger The trigger of execution
 * @param extraAttrs
 * @param startTime The start time of execution
 * @param endTime The end time of execution
 */

data class Execution(

    /* The ID of execution */
    @field:JsonProperty("id")
    val id: kotlin.Int? = null,

    /* The vendor type of execution */
    @field:JsonProperty("vendor_type")
    val vendorType: kotlin.String? = null,

    /* The vendor id of execution */
    @field:JsonProperty("vendor_id")
    val vendorId: kotlin.Int? = null,

    /* The status of execution */
    @field:JsonProperty("status")
    val status: kotlin.String? = null,

    /* The status message of execution */
    @field:JsonProperty("status_message")
    val statusMessage: kotlin.String? = null,

    @field:JsonProperty("metrics")
    val metrics: Metrics? = null,

    /* The trigger of execution */
    @field:JsonProperty("trigger")
    val trigger: kotlin.String? = null,

    @field:JsonProperty("extra_attrs")
    val extraAttrs: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* The start time of execution */
    @field:JsonProperty("start_time")
    val startTime: kotlin.String? = null,

    /* The end time of execution */
    @field:JsonProperty("end_time")
    val endTime: kotlin.String? = null

)

