/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id Unique ID
 * @param name Instance name
 * @param description Description of instance
 * @param vendor Based on which driver, identified by ID
 * @param endpoint The service endpoint of this instance
 * @param authMode The authentication way supported
 * @param authInfo The auth credential data if exists
 * @param status The health status
 * @param enabled Whether the instance is activated or not
 * @param default Whether the instance is default or not
 * @param insecure Whether the instance endpoint is insecure or not
 * @param setupTimestamp The timestamp of instance setting up
 */

data class Instance (

    /* Unique ID */
    @field:JsonProperty("id")
    val id: kotlin.Int? = null,

    /* Instance name */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Description of instance */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Based on which driver, identified by ID */
    @field:JsonProperty("vendor")
    val vendor: kotlin.String? = null,

    /* The service endpoint of this instance */
    @field:JsonProperty("endpoint")
    val endpoint: kotlin.String? = null,

    /* The authentication way supported */
    @field:JsonProperty("auth_mode")
    val authMode: kotlin.String? = null,

    /* The auth credential data if exists */
    @field:JsonProperty("auth_info")
    val authInfo: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* The health status */
    @field:JsonProperty("status")
    val status: kotlin.String? = null,

    /* Whether the instance is activated or not */
    @field:JsonProperty("enabled")
    val enabled: kotlin.Boolean? = null,

    /* Whether the instance is default or not */
    @field:JsonProperty("default")
    val default: kotlin.Boolean? = null,

    /* Whether the instance endpoint is insecure or not */
    @field:JsonProperty("insecure")
    val insecure: kotlin.Boolean? = null,

    /* The timestamp of instance setting up */
    @field:JsonProperty("setup_timestamp")
    val setupTimestamp: kotlin.Long? = null

)

