/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `value` The integer value of current config item
 * @param editable The configure item can be updated or not
 */

data class IntegerConfigItem (

    /* The integer value of current config item */
    @field:JsonProperty("value")
    val `value`: kotlin.Int? = null,

    /* The configure item can be updated or not */
    @field:JsonProperty("editable")
    val editable: kotlin.Boolean? = null

)

