/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param url The URL of OIDC endpoint to be tested.
 * @param verifyCert Whether the certificate should be verified
 */

data class PingOIDCRequest (

    /* The URL of OIDC endpoint to be tested. */
    @field:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Whether the certificate should be verified */
    @field:JsonProperty("verify_cert")
    val verifyCert: kotlin.Boolean? = null

)

