/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param hard 
 * @param used 
 */

data class ProjectSummaryQuota (

    @field:JsonProperty("hard")
    val hard: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null,

    @field:JsonProperty("used")
    val used: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null

)

