/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param deletable Whether the project can be deleted.
 * @param message The detail message when the project can not be deleted.
 */

data class ProjectDeletable (

    /* Whether the project can be deleted. */
    @field:JsonProperty("deletable")
    val deletable: kotlin.Boolean? = null,

    /* The detail message when the project can not be deleted. */
    @field:JsonProperty("message")
    val message: kotlin.String? = null

)

