/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param roleId The role id 1 for projectAdmin, 2 for developer, 3 for guest, 4 for maintainer
 * @param memberUser
 * @param memberGroup
 */

data class ProjectMember(

    /* The role id 1 for projectAdmin, 2 for developer, 3 for guest, 4 for maintainer */
    @field:JsonProperty("role_id")
    val roleId: kotlin.Int? = null,

    @field:JsonProperty("member_user")
    val memberUser: UserEntity? = null,

    @field:JsonProperty("member_group")
    val memberGroup: UserGroup? = null

)

