/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param provider 
 * @param enabled 
 * @param default 
 */

data class ProviderUnderProject (

    @field:JsonProperty("id")
    val id: kotlin.Int? = null,

    @field:JsonProperty("provider")
    val provider: kotlin.String? = null,

    @field:JsonProperty("enabled")
    val enabled: kotlin.Boolean? = null,

    @field:JsonProperty("default")
    val default: kotlin.Boolean? = null

)

