/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name The registry name.
 * @param description Description of the registry.
 * @param url The registry URL.
 * @param credentialType Credential type of the registry, e.g. 'basic'.
 * @param accessKey The registry access key.
 * @param accessSecret The registry access secret.
 * @param insecure Whether or not the certificate will be verified when Harbor tries to access the server.
 */

data class RegistryUpdate (

    /* The registry name. */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Description of the registry. */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* The registry URL. */
    @field:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Credential type of the registry, e.g. 'basic'. */
    @field:JsonProperty("credential_type")
    val credentialType: kotlin.String? = null,

    /* The registry access key. */
    @field:JsonProperty("access_key")
    val accessKey: kotlin.String? = null,

    /* The registry access secret. */
    @field:JsonProperty("access_secret")
    val accessSecret: kotlin.String? = null,

    /* Whether or not the certificate will be verified when Harbor tries to access the server. */
    @field:JsonProperty("insecure")
    val insecure: kotlin.Boolean? = null

)

