/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The request for robot account creation.
 *
 * @param name The name of the tag
 * @param description The description of the robot
 * @param secret The secret of the robot
 * @param level The level of the robot, project or system
 * @param disable The disable status of the robot
 * @param duration The duration of the robot in days
 * @param permissions
 */

data class RobotCreate(

    /* The name of the tag */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* The description of the robot */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* The secret of the robot */
    @field:JsonProperty("secret")
    val secret: kotlin.String? = null,

    /* The level of the robot, project or system */
    @field:JsonProperty("level")
    val level: kotlin.String? = null,

    /* The disable status of the robot */
    @field:JsonProperty("disable")
    val disable: kotlin.Boolean? = null,

    /* The duration of the robot in days */
    @field:JsonProperty("duration")
    val duration: kotlin.Long? = null,

    @field:JsonProperty("permissions")
    val permissions: kotlin.collections.List<RobotPermission>? = null

)

