/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The list of scan data export executions
 *
 * @param items The list of scan data export executions
 */

data class ScanDataExportExecutionList(

    /* The list of scan data export executions */
    @field:JsonProperty("items")
    val items: kotlin.collections.List<ScanDataExportExecution>? = null

)

