/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Name of the scanner
 * @param vendor Name of the scanner provider
 * @param version Version of the scanner adapter
 */

data class Scanner (

    /* Name of the scanner */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Name of the scanner provider */
    @field:JsonProperty("vendor")
    val vendor: kotlin.String? = null,

    /* Version of the scanner adapter */
    @field:JsonProperty("version")
    val version: kotlin.String? = null

)

