/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param id The id of the schedule.
 * @param status The status of the schedule.
 * @param creationTime the creation time of the schedule.
 * @param updateTime the update time of the schedule.
 * @param schedule
 * @param parameters The parameters of schedule job
 */

data class Schedule(

    /* The id of the schedule. */
    @field:JsonProperty("id")
    val id: kotlin.Int? = null,

    /* The status of the schedule. */
    @field:JsonProperty("status")
    val status: kotlin.String? = null,

    /* the creation time of the schedule. */
    @field:JsonProperty("creation_time")
    val creationTime: java.time.OffsetDateTime? = null,

    /* the update time of the schedule. */
    @field:JsonProperty("update_time")
    val updateTime: java.time.OffsetDateTime? = null,

    @field:JsonProperty("schedule")
    val schedule: ScheduleObj? = null,

    /* The parameters of schedule job */
    @field:JsonProperty("parameters")
    val parameters: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

