/**
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.edu.buaa.scs.sdk.harbor.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id The ID of the tag
 * @param repositoryId The ID of the repository that the tag belongs to
 * @param artifactId The ID of the artifact that the tag attached to
 * @param name The name of the tag
 * @param pushTime The push time of the tag
 * @param pullTime The latest pull time of the tag
 * @param immutable The immutable status of the tag
 * @param signed The attribute indicates whether the tag is signed or not
 */

data class Tag (

    /* The ID of the tag */
    @field:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* The ID of the repository that the tag belongs to */
    @field:JsonProperty("repository_id")
    val repositoryId: kotlin.Long? = null,

    /* The ID of the artifact that the tag attached to */
    @field:JsonProperty("artifact_id")
    val artifactId: kotlin.Long? = null,

    /* The name of the tag */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* The push time of the tag */
    @field:JsonProperty("push_time")
    val pushTime: java.time.OffsetDateTime? = null,

    /* The latest pull time of the tag */
    @field:JsonProperty("pull_time")
    val pullTime: java.time.OffsetDateTime? = null,

    /* The immutable status of the tag */
    @field:JsonProperty("immutable")
    val immutable: kotlin.Boolean? = null,

    /* The attribute indicates whether the tag is signed or not */
    @field:JsonProperty("signed")
    val signed: kotlin.Boolean? = null

)

