apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.cloudapi.scs.buaa.edu.cn
spec:
  group: cloudapi.scs.buaa.edu.cn
  names:
    kind: VirtualMachine
    plural: virtualmachines
    singular: virtualmachine
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.powerState
          name: spec_powerState
          type: string
        - jsonPath: .status.powerState
          name: status_powerState
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                name:
                  type: string
                platform:
                  type: string
                template:
                  type: boolean
                extraInfo:
                  type: string
                cpu:
                  type: integer
                memory:
                  type: integer
                diskNum:
                  type: integer
                diskSize:
                  type: integer
                powerState:
                  enum:
                    - value
                    - PoweredOff
                    - PoweredOn
                    - Suspended
                  type: string
                deleted:
                  type: boolean
              type: object
            status:
              properties:
                uuid:
                  type: string
                host:
                  type: string
                osFullName:
                  type: string
                powerState:
                  enum:
                    - value
                    - PoweredOff
                    - PoweredOn
                    - Suspended
                  type: string
                overallStatus:
                  enum:
                    - value
                    - Green
                    - Yellow
                    - Red
                    - Gray
                  type: string
                netInfos:
                  items:
                    properties:
                      macAddress:
                        type: string
                      ipList:
                        items:
                          type: string
                        type: array
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
