/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param userIds 需要删除的用户 ID 列表
 */
data class DeleteAdminUserRequest(
    /* 需要删除的用户 ID 列表 */
    val userIds: kotlin.collections.List<kotlin.String>
) 

