/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models

import cn.edu.buaa.scs.controller.models.ResourceModel

/**
 * 
 * @param expId 
 * @param resource 
 * @param configuration json string
 * @param name 
 * @param needSubmit 
 * @param studentIdList 
 */
data class ExperimentWorkflowConfigurationRequest(
    val expId: kotlin.Int,
    val resource: ResourceModel,
    /* json string */
    val configuration: kotlin.String,
    val name: kotlin.String,
    val needSubmit: kotlin.Boolean,
    val studentIdList: kotlin.collections.List<kotlin.String>? = null
) 

