/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models

import cn.edu.buaa.scs.controller.models.UserModel

/**
 * 
 * @param id 
 * @param expId 
 * @param resourcePool name of resourcePool crd
 * @param configuration json string
 * @param studentList 
 * @param name 
 * @param needSubmit 
 */
data class ExperimentWorkflowConfigurationResponse(
    val id: kotlin.Long,
    val expId: kotlin.Int,
    /* name of resourcePool crd */
    val resourcePool: kotlin.String,
    /* json string */
    val configuration: kotlin.String,
    val studentList: kotlin.collections.List<UserModel>,
    val name: kotlin.String,
    val needSubmit: kotlin.Boolean
) 

