/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param ip 
 * @param status 
 * @param totalMem 
 * @param usedMem 
 * @param totalCPU 
 * @param usedCPU 
 * @param totalStorage 
 * @param usedStorage 
 * @param count 
 */
data class Host(
    val ip: kotlin.String,
    val status: kotlin.String,
    val totalMem: kotlin.Double,
    val usedMem: kotlin.Double,
    val totalCPU: kotlin.Double,
    val usedCPU: kotlin.Double,
    val totalStorage: kotlin.Long,
    val usedStorage: kotlin.Long,
    val count: kotlin.Int
) 

