/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param endpoint 
 * @param ref 
 * @param scheme 
 * @param userPassword 
 * @param username 
 */
data class ImageBuilderSpecContextGit(
    val endpoint: kotlin.String,
    val ref: kotlin.String? = null,
    val scheme: ImageBuilderSpecContextGit.Scheme? = Scheme.https,
    val userPassword: kotlin.String? = null,
    val username: kotlin.String? = null
) 
{
    /**
    * 
    * Values: http,https
    */
    enum class Scheme(val value: kotlin.String){
        http("http"),
        https("https");
    }
}

