/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param accessKey 
 * @param secretKey 
 * @param endpoint 
 * @param scheme 
 * @param bucket 
 * @param key 
 * @param region 
 */
data class S3Config(
    val accessKey: kotlin.String,
    val secretKey: kotlin.String,
    val endpoint: kotlin.String,
    val scheme: kotlin.String,
    val bucket: kotlin.String,
    val key: kotlin.String,
    val region: kotlin.String
) 

