/**
* cloudapi_v2
* buaa scs cloud api v2
*
* The version of the OpenAPI document: 2.0
* Contact: loheagn@icloud.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cn.edu.buaa.scs.controller.models


/**
 * 
 * @param id 用户的唯一标识
 * @param role 用户角色
 * @param service 第三方服务名称
 */
data class TokenInfoResponseData(
    /* 用户的唯一标识 */
    val id: kotlin.String,
    /* 用户角色 */
    val role: kotlin.String,
    /* 第三方服务名称 */
    val service: kotlin.String
) 

