name: 'Build and Push Docker Image'

on:
  push:
    branch: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Build
        run: ./gradlew clean build -x test --no-daemon

      - name: Docker Build and Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.ALIYUN_DOCKER_NAMESPACE }}/cloudapi
          tags: ${{ github.ref_name }}
          registry: ${{ secrets.ALIYUN_DOCKER_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

